import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { ensureDir } from './utils.js';
import { AnalysisResult } from './analyzer.js';
import { ImprovementResult } from './improver.js';

export interface ExportOptions {
  outputDir?: string;
  format?: 'markdown' | 'json';
  includeRaw?: boolean;
}

export interface ExportResult {
  path: string;
  files: string[];
}

export function exportLearnings(
  analysis: AnalysisResult,
  improvements: ImprovementResult,
  options: ExportOptions = {}
): ExportResult {
  const outputDir = options.outputDir || join(process.cwd(), '.learnings');
  const format = options.format || 'markdown';
  
  ensureDir(outputDir);
  
  const timestamp = new Date().toISOString().split('T')[0];
  const files: string[] = [];
  
  // Export CLAUDE.md suggestion
  const claudeMdPath = join(outputDir, 'CLAUDE.md.suggested');
  writeFileSync(claudeMdPath, improvements.claudeMdSuggestion);
  files.push(claudeMdPath);
  
  // Export analysis report
  if (format === 'markdown') {
    const reportPath = join(outputDir, `analysis-${timestamp}.md`);
    writeFileSync(reportPath, formatMarkdownReport(analysis, improvements));
    files.push(reportPath);
  } else {
    const reportPath = join(outputDir, `analysis-${timestamp}.json`);
    writeFileSync(reportPath, JSON.stringify({ analysis, improvements }, null, 2));
    files.push(reportPath);
  }
  
  // Export raw patterns if requested
  if (options.includeRaw) {
    const rawPath = join(outputDir, `patterns-${timestamp}.json`);
    writeFileSync(rawPath, JSON.stringify(analysis.patterns, null, 2));
    files.push(rawPath);
  }
  
  return { path: outputDir, files };
}

function formatMarkdownReport(
  analysis: AnalysisResult,
  improvements: ImprovementResult
): string {
  const lines: string[] = [
    '# Claude Learner Analysis Report',
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Summary',
    '',
    `- **Sessions analyzed:** ${analysis.totalSessions}`,
    `- **Total messages:** ${analysis.totalMessages}`,
    `- **Patterns found:** ${analysis.patterns.length}`,
    `- **Improvements suggested:** ${improvements.improvements.length}`,
    '',
    '## Top Correction Patterns',
    ''
  ];
  
  const topPatterns = analysis.patterns.slice(0, 15);
  for (let i = 0; i < topPatterns.length; i++) {
    const p = topPatterns[i];
    lines.push(`### ${i + 1}. ${p.type.toUpperCase()}`);
    lines.push('');
    lines.push(`**Message:** "${p.userMessage.slice(0, 200)}"`);
    if (p.assistantContext) {
      lines.push('');
      lines.push(`**Context:** "${p.assistantContext.slice(0, 200)}"`);
    }
    lines.push('');
    lines.push(`**Frequency:** ${p.frequency}`);
    lines.push('');
  }
  
  lines.push('## Suggested Rules');
  lines.push('');
  
  for (const imp of improvements.improvements) {
    const priorityEmoji = imp.priority === 'high' ? '🔴' : imp.priority === 'medium' ? '🟡' : '🟢';
    lines.push(`- ${priorityEmoji} **[${imp.category}]** ${imp.rule}`);
    lines.push(`  - _${imp.reason}_`);
  }
  
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('_Generated by [claude-learner](https://github.com/your-org/claude-learner)_');
  
  return lines.join('\n');
}

export function formatExportResult(result: ExportResult): string {
  const lines: string[] = [
    chalk.bold.cyan('\n📁 Export Complete\n'),
    chalk.dim('─'.repeat(50)),
    '',
    `${chalk.bold('Output directory:')} ${result.path}`,
    '',
    chalk.bold('Files created:'),
    ''
  ];
  
  for (const file of result.files) {
    const filename = file.split('/').pop() || file;
    lines.push(`  📄 ${chalk.green(filename)}`);
  }
  
  lines.push('');
  lines.push(chalk.dim('─'.repeat(50)));
  lines.push('');
  lines.push(chalk.yellow('💡 Tip: Review CLAUDE.md.suggested and merge into your project\'s CLAUDE.md'));
  
  return lines.join('\n');
}
